name: Send an email

on:
  pull_request:
    branches: ['backend', 'dev', 'frontend']

jobs:
  test_pull_request:
    runs-on: ['ubuntu-latest', 'windows-latest']
    steps:
      -uses: actions/checkout@v2
      -uses: actions/setup-node@v1
        with:
          node-version: 18
          
